using Microsoft.CodeAnalysis;
using System.Text;
using Wiped.Roslyn;

namespace Wiped.Generators;

[Generator]
public sealed class ModuleGenerator : IIncrementalGenerator
{
	private const string FileName = "GeneratedModule.g.cs";
	private const string ClassName = "GeneratedModule";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
        context.RegisterSourceOutput(context.CompilationProvider, GenerateModule);
	}

	private static void GenerateModule(SourceProductionContext context, Compilation compilation)
	{
		if (compilation.GetTypeByMetadataName(ContentAssemblyAttribute) is not { } contentAssemblyAttribute)
			return;

		if (!compilation.Assembly.HasAttribute(contentAssemblyAttribute))
			return;

		var source = BuildSource(compilation, contentAssemblyAttribute);
		context.AddSource(FileName, source);
	}

	private static IEnumerable<string> GetModuleDependencies(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
		{
			// skip self
			if (SymbolEqualityComparer.Default.Equals(assembly, compilation.Assembly))
				continue;

			if (!assembly.HasAttribute(contentAssemblyAttribute))
				continue;

			var asmNamespace = assembly.GetGeneratorNamespace(compilation);
			var moduleName = $"{asmNamespace}.{ClassName}";

			yield return $"{moduleName}.Instance";
		}
	}

	private static string BuildSource(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{

		var sb = new StringBuilder();
		sb.AppendLine(
			$$"""
			using Wiped.Shared;
			using Wiped.Shared.IoC;

			namespace {{compilation.Assembly.GetGeneratorNamespace(compilation)}};

			// <auto-generated/>
			public partial class {{ClassName}} : IGeneratedModule
			{
				public static readonly GeneratedModule Instance = new();

			"""
		);

		BuildDependencies(sb, compilation, contentAssemblyAttribute);
		BuildIoC(sb, compilation);

		sb.AppendLine(
			"""
			}
			"""
		);

		return sb.ToString();
	}

	private static void BuildDependencies(StringBuilder sb, Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		var dependencies = GetModuleDependencies(compilation, contentAssemblyAttribute);

		if (!dependencies.Any())
			return;

		sb.AppendLine(
			"""
				public IReadOnlyList<IGeneratedModule> Dependencies => [
			"""
		);

		foreach (var dep in dependencies)
		{
			sb.AppendLine(
				$"""
						{dep},
				"""
			);
		}

		sb.AppendLine(
			"""
				];

			"""
		);
	}

	private static void BuildIoC(StringBuilder sb, Compilation compilation)
	{
		sb.AppendLine(
			"""
				public void RegisterIoC()
				{
			"""
		);

		if (compilation.GetTypeByMetadataName(AutoBindAttribute) is not { } autoBindSymbol)
		{
			sb.AppendLine(
				"""
					}
				"""
			);

			return;
		}

		foreach (var type in GetAllTypes(compilation.Assembly.GlobalNamespace))
		{
			if (type.TypeKind != TypeKind.Class)
				continue;

			if (type.GetAttribute(autoBindSymbol) is not { } attr)
				continue;

			var serviceTypes = GetServiceTypes(attr);
			if (!serviceTypes.Any())
				continue;

			foreach (var serviceType in serviceTypes)
			{
				sb.AppendLine(
					$"""
							IoCManager.Bind(typeof({serviceType}), typeof({type.ToDisplayString()}));
					"""
				);
			}
		}

		sb.AppendLine(
			"""
				}
			"""
		);
	}

	private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				foreach (var nested in GetAllTypes(ns))
					yield return nested;
			}
			else if (member is INamedTypeSymbol type)
			{
				yield return type;

				foreach (var nested in GetNestedTypes(type))
					yield return nested;
			}
		}
	}

	private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
	{
		foreach (var nested in type.GetTypeMembers())
		{
			yield return nested;

			foreach (var deeper in GetNestedTypes(nested))
				yield return deeper;
		}
	}

	private static IEnumerable<string> GetServiceTypes(AttributeData attr)
	{
		foreach (var arg in attr.ConstructorArguments)
		{
			if (arg.Kind == TypedConstantKind.Array)
			{
				// multiple services
				foreach (var item in arg.Values)
				{
					if (item.Value is INamedTypeSymbol sym)
						yield return sym.ToDisplayString();
				}
			}
			else if (arg.Value is INamedTypeSymbol sym)
			{
				yield return sym.ToDisplayString();
			}
		}
	}
}
