using Microsoft.CodeAnalysis;
using System.Text;
using Wiped.Roslyn;

namespace Wiped.Generators;

[Generator]
public sealed partial class ModuleGenerator : IIncrementalGenerator
{
	private const string FileName = "GeneratedModule.g.cs";
	private const string ClassName = "GeneratedModule";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
        context.RegisterSourceOutput(context.CompilationProvider, GenerateModule);
	}

	private static void GenerateModule(SourceProductionContext context, Compilation compilation)
	{
		if (compilation.GetTypeByMetadataName(ContentAssemblyAttribute) is not { } contentAssemblyAttribute)
			return;

		if (!compilation.Assembly.HasAttribute(contentAssemblyAttribute))
			return;

		var source = BuildSource(compilation, contentAssemblyAttribute);
		context.AddSource(FileName, source);
	}

	private static IEnumerable<string> GetModuleDependencies(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		foreach (var assembly in compilation.GetContentAssemblies(contentAssemblyAttribute))
		{
			var asmNamespace = assembly.GetGeneratorNamespace(compilation, contentAssemblyAttribute);
			var moduleName = $"{asmNamespace}.{ClassName}";

			yield return $"{moduleName}.Instance";
		}
	}

	private static string BuildSource(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		var sb = new StringBuilder();
		sb.AppendLine(
			$$"""
			using Wiped.Shared;
			using Wiped.Shared.IoC;
			using Wiped.Shared.Reflection;

			namespace {{compilation.Assembly.GetGeneratorNamespace(compilation)}};

			// <auto-generated/>
			public sealed class {{ClassName}} : IGeneratedModule
			{
				public static readonly GeneratedModule Instance = new();

			"""
		);

		BuildDependencies(sb, compilation, contentAssemblyAttribute);
		BuildIoC(sb, compilation);
		BuildReflectionRegistry(sb, compilation);

		sb.AppendLine(
			"""
			}
			"""
		);

		return sb.ToString();
	}

	private static void BuildDependencies(StringBuilder sb, Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		var dependencies = GetModuleDependencies(compilation, contentAssemblyAttribute);

		if (!dependencies.Any())
			return;

		sb.AppendLine(
			"""
				public IReadOnlyList<IGeneratedModule> Dependencies => [
			"""
		);

		foreach (var dep in dependencies)
		{
			sb.AppendLine(
				$"""
						{dep},
				"""
			);
		}

		sb.AppendLine(
			"""
				];

			"""
		);
	}
}
