using Microsoft.CodeAnalysis;
using System.Diagnostics;
using System.Text;
using Wiped.Roslyn;

namespace Wiped.Generators;

[Generator]
public sealed class ModuleGenerator : IIncrementalGenerator
{
	private const string FileName = "GeneratedModule.g.cs";
	private const string ClassName = "GeneratedModule";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
        context.RegisterSourceOutput(context.CompilationProvider, GenerateModule);
	}

	private static void GenerateModule(SourceProductionContext context, Compilation compilation)
	{
		if (compilation.GetTypeByMetadataName(ContentAssemblyAttribute) is not { } contentAssemblyAttribute)
			return;

		if (!compilation.Assembly.HasAttribute(contentAssemblyAttribute))
			return;

		var source = BuildSource(compilation, contentAssemblyAttribute);
		context.AddSource(FileName, source);
	}

	private static IEnumerable<string> GetModuleDependencies(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		foreach (var assembly in compilation.GetContentAssemblies(contentAssemblyAttribute))
		{
			var asmNamespace = assembly.GetGeneratorNamespace(compilation, contentAssemblyAttribute);
			var moduleName = $"{asmNamespace}.{ClassName}";

			yield return $"{moduleName}.Instance";
		}
	}

	private static string BuildSource(Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{

		var sb = new StringBuilder();
		sb.AppendLine(
			$$"""
			using Wiped.Shared;
			using Wiped.Shared.IoC;

			namespace {{compilation.Assembly.GetGeneratorNamespace(compilation)}};

			// <auto-generated/>
			public partial class {{ClassName}} : IGeneratedModule
			{
				public static readonly GeneratedModule Instance = new();

			"""
		);

		BuildDependencies(sb, compilation, contentAssemblyAttribute);
		BuildIoC(sb, compilation);

		sb.AppendLine(
			"""
			}
			"""
		);

		return sb.ToString();
	}

	private static void BuildDependencies(StringBuilder sb, Compilation compilation, INamedTypeSymbol contentAssemblyAttribute)
	{
		var dependencies = GetModuleDependencies(compilation, contentAssemblyAttribute);

		if (!dependencies.Any())
			return;

		sb.AppendLine(
			"""
				public IReadOnlyList<IGeneratedModule> Dependencies => [
			"""
		);

		foreach (var dep in dependencies)
		{
			sb.AppendLine(
				$"""
						{dep},
				"""
			);
		}

		sb.AppendLine(
			"""
				];

			"""
		);
	}

	private static void BuildIoC(StringBuilder sb, Compilation compilation)
	{
		sb.AppendLine(
			"""
				public void RegisterIoC()
				{
			"""
		);

		if (compilation.GetTypeByMetadataName(AutoBindAttribute) is not { } autoBindSymbol)
		{
			sb.AppendLine(
				"""
					}
				"""
			);

			return;
		}

		foreach (var type in compilation.Assembly.GlobalNamespace.GetAllTypes())
		{
			if (type.TypeKind != TypeKind.Class)
				continue;

			if (type.GetAttribute(autoBindSymbol) is not { } attr)
				continue;

			foreach (var serviceSymbol in GetServiceTypeSymbols(attr))
			{
				var serviceName = serviceSymbol.ToDisplayString();
				var implName = type.ToDisplayString();

				sb.AppendLine(
					$"""
							IoCManager.Bind<{serviceName}, {implName}>();
					"""
				);
			}
		}

		sb.AppendLine(
			"""
				}
			"""
		);
	}

	private static IEnumerable<INamedTypeSymbol> GetServiceTypeSymbols(AttributeData attr)
	{
		foreach (var arg in attr.ConstructorArguments)
		{
			if (arg.Kind == TypedConstantKind.Array)
			{
				// multiple services
				foreach (var item in arg.Values)
				{
					if (item.Value is INamedTypeSymbol sym)
						yield return sym;
				}
			}
			else if (arg.Value is INamedTypeSymbol sym)
			{
				yield return sym;
			}
		}
	}
}
